tb=int(input('digite um numero para ver sua tabuada:'))
print("-"*12)
print('{}x{:2}={}'.format(tb,1,tb*1))
print('{}x{:2}={}'.format(tb,2,tb*2))
print('{}x{:2}={}'.format(tb,3,tb*3))
print('{}x{:2}={}'.format(tb,4,tb*4))
print('{}x{:2}={}'.format(tb,5,tb*5))
print('{}x{:2}={}'.format(tb,6,tb*6))
print('{}x{:2}={}'.format(tb,7,tb*7))
print('{}x{:2}={}'.format(tb,8,tb*8))
print('{}x{:2}={}'.format(tb,9,tb*9))
print('{}x{:2}={}'.format(tb,10,tb*10))
print('-'*12)