a = input ('digite algo')
print('o tipo primitivo desse valor e', type(a))
print('so tem espacos?', a.isspace())
print('e um numero?', a.isnumeric())
print('e afalbetico?', a.isalpha())
print('e alphanumerico?', a.isalnum())
print('esta em maiusculas?',a.isupper())
print('esta em minusculas?',a.islower())
print('esta capitalizada?',a.istitle())